- Apply ()
- Datetimes
- Groupby ()
- Agg()

In [57]:
import pandas as pd

df = pd.read_csv("./data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [58]:
for col in df.columns:
    print(f"{col} is numeric?: {pd.api.types.is_numeric_dtype(df[col])}")

id is numeric?: True
name is numeric?: False
place is numeric?: False
year is numeric?: True
lat is numeric?: True
long is numeric?: True
lat_long is numeric?: False

In [59]:
from random import choice, seed

seed(41)

def my_function(x):
    print(x)
df["date_start"] = df["year"].apply(lambda x:f"{x}-{choice(range(1,13)):02d}-{choice(range(1,29))}")

df.head()

,id,name,place,year,lat,long,lat_long,date_start
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57",1543-07-11
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57",1541-04-6
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",1561-07-19
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57",1563-12-10
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57",1582-09-9

In [60]:
# drop the column year_start
df.drop(columns=["date_start"])

,id,name,place,year,lat,long,lat_long
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57"
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57"
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57"
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57"
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57"
...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33"
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45"
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33"
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33"
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36"

In [64]:
# making the year_start better by using a named function
import numpy as np
def get_year_end(row):
    rows = df.loc[
        (df["name"]==row["name"])&
        (df["place"]==row["place"])&
        (df["year"]==row["year"]+1)
    ]
    if len(rows) > 0:
        return np.nan
    date_string = f"{row["year"]}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
    return date_string

df["date_end"]= df.apply(get_year_end, axis=1) # on a df, must pass axis
df.head()

,index,id,name,place,year,lat,long,lat_long,date_start,date_end
0,422,422,"Danzay, Charles de",Denmark,1557,55.68,12.57,"55.68, 12.57",1557-07-2,NaN
1,638,638,"Danzay, Charles de",Denmark,1558,55.68,12.57,"55.68, 12.57",1558-06-15,NaN
2,704,704,"Danzay, Charles de",Denmark,1559,55.68,12.57,"55.68, 12.57",1559-08-22,NaN
3,421,421,"Danzay, Charles de",Denmark,1560,55.68,12.57,"55.68, 12.57",1560-12-20,NaN
4,2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",1561-07-19,NaN

In [65]:
# bfill: back fill ffill: forward fill
df = df.sort_values(["place","name","year"],ascending=True).reset_index()
df.head()

,level_0,index,id,name,place,year,lat,long,lat_long,date_start,date_end
0,0,422,422,"Danzay, Charles de",Denmark,1557,55.68,12.57,"55.68, 12.57",1557-07-2,NaN
1,1,638,638,"Danzay, Charles de",Denmark,1558,55.68,12.57,"55.68, 12.57",1558-06-15,NaN
2,2,704,704,"Danzay, Charles de",Denmark,1559,55.68,12.57,"55.68, 12.57",1559-08-22,NaN
3,3,421,421,"Danzay, Charles de",Denmark,1560,55.68,12.57,"55.68, 12.57",1560-12-20,NaN
4,4,2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",1561-07-19,NaN

In [66]:
df["date_start"] =  df["date_start"].ffill()
df["date_end"] = df["date_end"].bfill()
df.head()

,level_0,index,id,name,place,year,lat,long,lat_long,date_start,date_end
0,0,422,422,"Danzay, Charles de",Denmark,1557,55.68,12.57,"55.68, 12.57",1557-07-2,1589-10-15
1,1,638,638,"Danzay, Charles de",Denmark,1558,55.68,12.57,"55.68, 12.57",1558-06-15,1589-10-15
2,2,704,704,"Danzay, Charles de",Denmark,1559,55.68,12.57,"55.68, 12.57",1559-08-22,1589-10-15
3,3,421,421,"Danzay, Charles de",Denmark,1560,55.68,12.57,"55.68, 12.57",1560-12-20,1589-10-15
4,4,2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",1561-07-19,1589-10-15

In [ ]:
import datetime
fmt = "%Y-%M-%d"

df["date_start"] =  df["date_start"].apply(datetime.datetime.strptime())

TypeError: strptime() takes exactly 2 arguments (0 given)

In [68]:
df.groupby(["place"]).count()

,level_0,index,id,name,year,lat,long,lat_long,date_start,date_end
place,,,,,,,,,,
Denmark,40,40,40,40,40,40,40,40,40,40
England,93,93,93,93,93,93,93,93,93,93
Ferrara,3,3,3,3,3,3,3,3,3,3
Geneva,2,2,2,2,2,2,2,2,2,2
Grisons,77,77,77,77,77,77,77,77,77,77
Holy Roman Empire,81,81,81,81,81,81,81,81,81,81
Netherlands,45,45,45,45,45,45,45,45,45,45
Ottoman Empire,89,89,89,89,89,89,89,89,89,89
Poland,7,7,7,7,7,7,7,7,7,7
Portugal,56,56,56,56,56,56,56,56,56,56
Rome,82,82,82,82,82,82,82,82,82,82
Savoy,4,4,4,4,4,4,4,4,4,4
Saxony,3,3,3,3,3,3,3,3,3,3
Scotland,22,22,22,22,22,22,22,22,22,22
Spain,35,35,35,35,35,35,35,35,35,35
Swiss Cantons,131,131,131,131,131,131,131,131,131,131
Tuscany,3,3,3,3,3,3,3,3,3,3
Venice,96,96,96,96,96,96,96,96,96,96

In [69]:
df.groupby(["place"]).agg(
    {
        "place": "count",
        "year": "min",
    }
)

                   place  year
place
Denmark               40  1541
England               93  1516
Ferrara                3  1535
Geneva                 2  1559
Grisons               77  1525
Holy Roman Empire     81  1519
Netherlands           45  1529
Ottoman Empire        89  1535
Poland                 7  1572
Portugal              56  1522
Rome                  82  1513
Savoy                  4  1528
Saxony                 3  1570
Scotland              22  1548
Spain                 35  1559
Swiss Cantons        131  1522
Tuscany                3  1527
Venice                96  1516

In [72]:
df.groupby(["place"]).agg(
    place_years=("place", "count"),
    max=("year","max"),
    min=("year", "min"),
    num_ambs=("name","nunique"),
    ambs=("name", "unique")    
).reset_index(drop=True)

,place_years,max,min,num_ambs,ambs
0,40,1589,1541,2,"[Danzay, Charles de, Richer, Christophe]"
1,93,1600,1516,26,"[Bapaume, Robert de, Bochetel, Jacques, Castel..."
2,3,1554,1535,2,"[Du Gabre, Dominique, Langeac, Jean de]"
3,2,1560,1559,1,"[Boistaillé, Jean Hurault de]"
4,77,1588,1525,13,"[Bellièvre, Pomponne de, Cambray, Jean-Jacques..."
5,81,1600,1519,15,"[Ancel, Guillaume, Bochetel, Bernardin, Calvim..."
6,45,1600,1529,12,"[Blatier, Claude, Bochetel, Jacques, Choary, P..."
7,89,1600,1535,20,"[Berthier, Sébastien, Cambray, Jacques de, Cot..."
8,7,1574,1572,5,"[Fayes, Jacques, sr d'Espesses, Lansac, Guy de..."
9,56,1578,1522,5,"[De Caix, Honoré, De Seurre, Miguel, Nicot, Je..."
10,82,1589,1513,24,"[Adhemar, Louis, Babou, Philibert, Carmain, Pa..."
11,4,1574,1528,3,"[Des Barres, Louis, Henri d'Angouleme, Sr. de ..."
12,3,1572,1570,1,"[Schomberg, Gaspard de]"
13,22,1588,1548,4,"[Clutin, Henri, Courcelles, Baron de, Du Croc,..."
14,35,1589,1559,5,"[Fourquevaux, Raymond de Beccarie de Pavie, Ba..."
15,131,1600,1522,27,"[Bellièvre, Jean de, sr. de Hautefort, Bellièv..."
16,3,1529,1527,1,"[Dodieu, Claude]"
17,96,1600,1516,20,"[Boistaillé, Jean Hurault de, Canossa, Louis d..."